package candi.web.routes;

import candi.runtime.CandiRoute;
import candi.runtime.Page;
import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.beans.factory.config.ConfigurableListableBeanFactory;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.stereotype.Component;

/**
 * Scans all bean definitions at startup to discover {@code @Page} and
 * {@code @CandiRoute} annotated classes, then registers them as named routes.
 *
 * <p>Route name derivation: strips "Page" suffix from the class simple name
 * and converts camelCase to UPPER_SNAKE_CASE.
 * <ul>
 *   <li>{@code PostsPage} becomes {@code POSTS}</li>
 *   <li>{@code EditPostPage} becomes {@code EDIT_POST}</li>
 *   <li>{@code IndexPage} becomes {@code INDEX}</li>
 * </ul>
 */
@Component
public class RoutesRegistry {

    private static final Logger log = LoggerFactory.getLogger(RoutesRegistry.class);

    private final ApplicationContext applicationContext;

    public RoutesRegistry(ApplicationContext applicationContext) {
        this.applicationContext = applicationContext;
    }

    @PostConstruct
    public void scanRoutes() {
        Routes.clear();

        ConfigurableListableBeanFactory beanFactory =
                ((ConfigurableApplicationContext) applicationContext).getBeanFactory();

        int count = 0;

        for (String beanName : beanFactory.getBeanDefinitionNames()) {
            BeanDefinition bd = beanFactory.getBeanDefinition(beanName);
            String className = bd.getBeanClassName();
            if (className == null) continue;

            try {
                Class<?> beanClass = Class.forName(className);
                String path = null;

                // Check @CandiRoute first (generated by compiler)
                CandiRoute candiRoute = beanClass.getAnnotation(CandiRoute.class);
                if (candiRoute != null) {
                    path = candiRoute.path();
                }

                // Check @Page annotation
                if (path == null) {
                    Page page = beanClass.getAnnotation(Page.class);
                    if (page != null) {
                        path = page.value();
                    }
                }

                if (path != null) {
                    String routeName = deriveRouteName(beanClass.getSimpleName());
                    Route route = new Route(path);
                    Routes.register(routeName, route);
                    count++;
                    log.debug("Registered route: {} -> {} ({})", routeName, path, beanClass.getSimpleName());
                }
            } catch (ClassNotFoundException e) {
                // Not loadable, skip
            }
        }

        log.info("Candi RoutesRegistry: {} route(s) registered", count);
    }

    /**
     * Derive a route name from a page class simple name.
     * Strips "Page" suffix and converts camelCase to UPPER_SNAKE_CASE.
     */
    static String deriveRouteName(String simpleName) {
        // Strip "Page" suffix
        String name = simpleName;
        if (name.endsWith("Page") && name.length() > 4) {
            name = name.substring(0, name.length() - 4);
        }

        // Convert camelCase to UPPER_SNAKE_CASE
        StringBuilder result = new StringBuilder();
        for (int i = 0; i < name.length(); i++) {
            char c = name.charAt(i);
            if (Character.isUpperCase(c) && i > 0) {
                result.append('_');
            }
            result.append(Character.toUpperCase(c));
        }

        return result.toString();
    }
}
